/* Auto generated by typedotenv */
if (typeof process.env.TOKEN !== "string")
	throw new Error("TOKEN is not defined in .env");
export const TOKEN = process.env.TOKEN;
if (typeof process.env.OPENAI_API_KEY !== "string")
	throw new Error("OPENAI_API_KEY is not defined in .env");
export const OPENAI_API_KEY = process.env.OPENAI_API_KEY;
