name: fmt

on:
  push:

permissions:
  contents: read
jobs:
  test:
    runs-on: Ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno lint -c deno.jsonc
      - run: deno fmt -c deno.jsonc --check
